apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: calvinpuram.com
  namespace: default
spec:
  secretName: calvinpuram.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: calvinpuram.com
  dnsNames:
    - calvinpuram.com
